config/routes.rb
Rails.application.routes.draw do
  root 'game_nights#index'

  resources :players do
    resource :game_library, only: %i(show new create update)
  end

  resources :games, only: %i(show)
  resources :game_nights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board_game_geek.rb
class BoardGameGeek
end

app/models/board_game_geek/game.rb
class BoardGameGeek
  class Game
    attr_reader :id, :name, :picture, :rating

    def initialize(id:, name:, picture:, rating:)
      @id = id
      @name = name
      @picture = picture
      @rating = rating
    end
  end
end

app/models/board_game_geek/service.rb
class BoardGameGeek
  class Service
    def collection(username:)
      res = client.get("collection/#{username}", { own: 1 })

      case res.status
      when 202 # accepted
        sleep 1
        collection(username:)
      when 200
        res.body.dig('items', 'item').map do |item|
          Game.new(
            id: item['objectid'],
            name: item.dig('name', '__content__'),
            picture: item['thumbnail'],
            rating: item.dig('stats', 'rating', 'bayesaverage', 'value').to_f
          )
        end
      else
        raise 'Something went wrong'
      end
    end

    private

    def client
      return @client if @client

      @client = Faraday.new(url: 'https://api.geekdo.com/xmlapi') do |f|
        f.response :xml
        f.adapter :httpclient
      end
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_libraries

  validates :name, presence: true
  validates :external_id, presence: true
  validates :picture_url, presence: true
  validates :rating, presence: true
end

app/models/game_in_library.rb
class GameInLibrary < ApplicationRecord
  self.table_name = 'games_in_libraries'

  belongs_to :game_library
  belongs_to :game
end

app/models/game_library.rb
class GameLibrary < ApplicationRecord
  belongs_to :player
  has_many :games_in_library, class_name: 'GameInLibrary', foreign_key: 'game_library_id'
  has_many :games, through: :games_in_library

  validates :bgg_username, presence: true
end

app/models/game_night.rb
class GameNight < ApplicationRecord
  has_many :players

  validates :title, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game_night, optional: true

  has_one :game_library

  validates :name, presence: true
  validates :email, presence: true
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: -> { request.format.json? }
end

app/controllers/game_libraries_controller.rb
class GameLibrariesController < ApplicationController
  before_action :set_player

  def show
    @game_library = @player.game_library

    if @game_library
      render :show
    else
      render :not_found, status: :not_found
    end
  end

  def new
    @game_library = @player.build_game_library
  end

  def update
    @game_library = @player.game_library

    BoardGameGeek::FetchCollectionJob.perform_later @game_library

    render :show
  end

  def create
    @game_library = @player.build_game_library(game_library_params)

    respond_to do |format|
      if @game_library.save
        format.html { redirect_to player_game_library_url(player_id: @player), notice: "Ludothek wurde erfolgreich angelegt." }
        format.json { render :show, status: :created, location: @game_library }

        BoardGameGeek::FetchCollectionJob.perform_later @game_library
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_library.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_player
    @player = Player.find(params[:player_id])
  end

  def game_library_params
    params.require(:game_library).permit(:bgg_username)
  end
end

app/controllers/game_nights_controller.rb
class GameNightsController < ApplicationController
  before_action :set_game_night, only: %i[ show edit update destroy ]

  # GET /game_nights or /game_nights.json
  def index
    @game_nights = GameNight.all
  end

  # GET /game_nights/1 or /game_nights/1.json
  def show
  end

  # GET /game_nights/new
  def new
    @game_night = GameNight.new
  end

  # GET /game_nights/1/edit
  def edit
  end

  # POST /game_nights or /game_nights.json
  def create
    @game_night = GameNight.new(game_night_params)

    respond_to do |format|
      if @game_night.save
        format.html { redirect_to game_night_url(@game_night), notice: "Spieleabend wurde erfolgreich angelegt." }
        format.json { render :show, status: :created, location: @game_night }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_night.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_nights/1 or /game_nights/1.json
  def update
    respond_to do |format|
      if @game_night.update(game_night_params)
        format.html { redirect_to game_night_url(@game_night), notice: "Spieleabend wurde erfolgreich gespeichert." }
        format.json { render :show, status: :ok, location: @game_night }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_night.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_nights/1 or /game_nights/1.json
  def destroy
    @game_night.destroy

    respond_to do |format|
      format.html { redirect_to game_nights_url, notice: "Spieleabend wurde erfolgreich gelöscht." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game_night
    @game_night = GameNight.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_night_params
    params.require(:game_night).permit(:title, :takes_place_at)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show ]

  def show
    if request.headers['X-Embed-Link']
      render :show, layout: false
    else
      render :show
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Spieler:in wurde erfolgreich angelegt." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Spieler:in wurde erfolgreich gespeichert." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Spieler:in wurde erfolgreich gelöscht." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:name, :email, :nickname, :game_night_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_nights_helper.rb
module GameNightsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/application/_loading_animation.html.haml
%loading-animation{ "refresh-delay": 2000 }
  %aside
    = yield
    .lds-ellipsis
      %div
      %div
      %div
      %div
    = link_to "Neuladen", refresh_url, class: "LoadingAnimation_refreshLink"

app/views/game_libraries/new.html.haml
%h1 Neue Ludothek anlegen

= form_with(model: @game_library, url: player_game_library_path(player_id: @player)) do |form|
  - if @game_library.errors.any?
    %article
      %bold
        = "#{@game_library.errors.count} Fehler haben das Speichern verhindert!"
      %ul
        - @game_library.errors.each do |error|
          %li= error.full_message
  %p
    = form.label :bgg_username
    = form.text_field :bgg_username

  = form.submit

= link_to "Abbrechen", player_path(@player)

app/views/game_libraries/not_found.html.haml
%h1= "#{@player.name} hat noch keine Ludothek 😢"

%p Leg doch hier eine #{link_to("neue Ludothek", new_player_game_library_path(player_id: @player))} an!

app/views/game_libraries/show.html.haml
%h1 Ludothek von #{@player.name} (#{pluralize(@game_library.games.count, 'Spiel', plural: 'Spiele')})

- if @game_library.bgg_sync_completed?
  %ul.GameLibrary_gamesList
    - @game_library.games.each do |game|
      %li.GameLibrary_gamesList_item
        %embed-link= link_to game_path(game), game_path(game)
- else
  = render 'application/loading_animation', refresh_url: player_game_library_path(player_id: @player) do
    %p
      Daten werden von BoardGameGeek geladen

    = button_to player_game_library_path(player_id: @player), method: "put" do
      = "Ludothek von BGG laden"

app/views/game_nights/_form.html.haml
= form_with(model: game_night) do |form|
  - if game_night.errors.any?
    %article
      %bold
        = "#{game_night.errors.count} Fehler haben das Speichern verhindert!"
      %ul
        - game_night.errors.each do |error|
          %li= error.full_message
  %p
    = form.label :title
    = form.text_field :title
  %p
    = form.label :takes_place_at
    = form.datetime_field :takes_place_at

  = form.submit

app/views/game_nights/_game_night.html.haml
%div{:id => "#{dom_id game_night}"}
  %p
    %strong Titel:
    = game_night.title
  %p
    %strong Wann?:
    = game_night.takes_place_at
  %p
    %strong Spieler:innen:
    %ul
      - game_night.players.each do |player|
        %li= link_to player.name, player_url(player)

app/views/game_nights/edit.html.haml
%h1 Spieleabend bearbeiten

= render "form", game_night: @game_night

= link_to "Abbrechen", @game_night

app/views/game_nights/index.html.haml
%h1 Spieleabende

#game_nights
  %table
    %thead
      %tr
        %th Titel
        %th Wann?
        %th Spieler:innen
    %tbody
      - @game_nights.each do |game_night|
        %tr{id: "#{dom_id game_night}"}
          %th= link_to game_night.title, game_night
          %th= l game_night.takes_place_at
          %th
            %ul
              - game_night.players.each do |player|
                %li= link_to player.name, player_url(player)

= link_to new_game_night_path do
  %button Neuen Spieleabend

app/views/game_nights/new.html.haml
%h1 Neuer Spieleabend

= render "form", game_night: @game_night

= link_to "Abbrechen", game_nights_path

app/views/game_nights/show.html.haml
= render @game_night

= link_to "Editieren", edit_game_night_path(@game_night)
= link_to "Zurück", game_nights_path
= button_to "Löschen", @game_night, method: :delete

app/views/games/show.html.haml
.Game
  = image_tag @game.picture_url, class: "Game_picture"
  .Game_name= link_to @game.name, game_path(@game)
  .Game_rating
    %span= number_with_precision(@game.rating, precision: 1)

app/views/layouts/application.html.haml
!!!
%html{lang: "de"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %p{:style => "color: green"}= notice

    = yield

app/views/players/_form.html.haml
= form_with(model: player) do |form|
  - if player.errors.any?
    %article
      %bold
        = "#{player.errors.count} Fehler haben das Speichern verhindert!"
      %ul
        - player.errors.each do |error|
          %li= error.full_message
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :email
    = form.text_field :email
  %p
    = form.label :nickname
    = form.text_field :nickname
  %p
    = form.label :game_night_id
    = form.text_field :game_night_id

  = form.submit

app/views/players/_player.html.haml
%div{:id => "#{dom_id player}"}
  %p
    %strong Name:
    = player.name
  %p
    %strong E-Mail:
    = player.email
  %p
    %strong Nickname:
    = player.nickname
  %p
    %strong Spieleabend:
    = player.game_night_id

= link_to "Zur Ludothek von #{player.name}", player_game_library_path(player_id: player)

app/views/players/edit.html.haml
%h1 Spieler:in bearbeiten

= render "form", player: @player

= link_to "Abbrechen", @player

app/views/players/index.html.haml
%h1 Spieler:innen

#players
  %table
    %thead
      %tr
        %th Name
        %th Nickname
    %tbody
    - @players.each do |player|
      %tr{id: "#{dom_id player}"}
        %th= link_to player.name, player
        %th= player.nickname

= link_to new_player_path do
  %button Neue Spieler:in

app/views/players/new.html.haml
%h1 Neue Spieler:in

= render "form", player: @player

= link_to "Abbrechen", players_path

app/views/players/show.html.haml
= render @player

= link_to "Editieren", edit_player_path(@player)
= link_to "Zurück", players_path
= button_to "Löschen", @player, method: :delete